baseURL = "https://uyennbu.github.io/"
canonifyURLs = true    # chuy·ªÉn m·ªçi ƒë∆∞·ªùng d·∫´n th√†nh tuy·ªát ƒë·ªëi d·ª±a tr√™n baseURL
relativeURLs = false   # (tu·ª≥ ch·ªçn) ƒë·ªÉ link kh√¥ng b·ªã chuy·ªÉn th√†nh t∆∞∆°ng ƒë·ªëi
languageCode = "en-us"
title = "Uyen's blog"
theme = "PaperMod"

[taxonomies]
  tag = "tags"
#   category = "categories"
  series = "series"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['$', '$']]

[params]
    ShowMenu = true
    ShowBreadCrumbs = true
    ShowReadingTime = true
    ShowPostNavLinks = true
    ShowShareButtons = true
    ShowToc = true

    math = true

    [params.homeInfoParams]
        Title = "Hi there"
        Content = "Welcome to my blog. Here you can read about statistics, machine learning, environment and my journey at University of Science, Hanoi. Read fun! üòÅ"

    [[params.socialIcons]]
        name = "facebook"
        url = "https://www.facebook.com/bich.uyen.643513"
    
    [[params.socialIcons]]
        name = "linkedin"
        url = "https://www.linkedin.com/in/uyen-nguyen-bich-3875862ba/"

    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/uyennbu"

    [params.cover]
        linkFullImages = true

[menu]
    # [[menu.main]]
    #     identifier = "categories"
    #     name = "Categories"
    #     url = "/categories/"
    #     weight = 10

    [[menu.main]]
        identifier = "series"
        name = "Series"
        url = "/series/"
        weight = 10
    
    [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 20 # used to identify the order of the elements

    [[menu.main]]
        identifier = "archives"
        name = "Archives"
        url = "/archives/"
        weight = 30

    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 40

    