baseURL = "https://uyennbu.github.io/"
canonifyURLs = true    # chuyá»ƒn má»i Ä‘Æ°á»ng dáº«n thÃ nh tuyá»‡t Ä‘á»‘i dá»±a trÃªn baseURL
relativeURLs = false   # (tuá»³ chá»n) Ä‘á»ƒ link khÃ´ng bá»‹ chuyá»ƒn thÃ nh tÆ°Æ¡ng Ä‘á»‘i
languageCode = "en-us"
title = "Uyen's blog"
theme = "PaperMod"

[taxonomies]
  tag = "tags"
#   category = "categories"
  series = "series"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['$', '$']]

[params]
    ShowMenu = true
    ShowBreadCrumbs = true
    ShowReadingTime = true
    ShowPostNavLinks = true
    ShowShareButtons = true
    ShowToc = true

    math = true

    [params.homeInfoParams]
        Title = "Hello, have a fun and happy day! â˜˜ï¸"
        Content = """
ðŸŒ» Xin chÃ o, mÃ¬nh lÃ  UyÃªn vÃ  Ä‘Ã¢y lÃ  bog nhá» cá»§a mÃ¬nh, nÆ¡i mÃ¬nh chia sáº» vá» nhá»¯ng kiáº¿n thá»©c vÃ  nhá»¯ng cáº£m nháº­n cá»§a cÃ¡ nhÃ¢n mÃ¬nh trong quÃ¡ trÃ¬nh há»c Ä‘áº¡i há»c. Do mÃ¬nh Ä‘á»c vÃ  viáº¿t láº¡i nÃªn cÃ³ thá»ƒ cÃ²n nhiá»u sai sÃ³t nÃªn náº¿u phÃ¡t hiá»‡n ra lá»—i sai hoáº·c cáº§n gÃ³p Ã½ thÃ¬ báº¡n cá»© email cho mÃ¬nh nhÃ©, mÃ¬nh sáº½ ráº¥t vui khi nháº­n Ä‘Æ°á»£c sá»± gÃ³p Ã½ tá»« má»i ngÆ°á»i

ðŸŒ» Cáº£m Æ¡n báº¡n vÃ¬ Ä‘Ã£ giÃ nh thá»i gian cho mÃ¬nh, chÃºc báº¡n má»™t ngÃ y tá»‘t lÃ nh :>.

áº¢nh hoa cover mÃ¬nh láº¥y trÃªn Pinterest: https://www.pinterest.com/pin/3870349675132799/"""

    [[params.socialIcons]]
        name = "facebook"
        url = "https://www.facebook.com/bich.uyen.643513"
    
    [[params.socialIcons]]
        name = "linkedin"
        url = "https://www.linkedin.com/in/uyen-nguyen-bich-3875862ba/"

    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/uyennbu"

    [[params.socialIcons]]
        name = "email"
        url = "mailto:uyennguyen.nbu@gmail.com"

    [params.cover]
        linkFullImages = false

[menu]
    # [[menu.main]]
    #     identifier = "categories"
    #     name = "Categories"
    #     url = "/categories/"
    #     weight = 10

    [[menu.main]]
        identifier = "series"
        name = "Series"
        url = "/series/"
        weight = 10
    
    [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 20 # used to identify the order of the elements

    [[menu.main]]
        identifier = "archives"
        name = "Archives"
        url = "/archives/"
        weight = 30

    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 40

    