baseURL = "https://nguyen451.github.io/"
languageCode = "en-us"
title = "Uyen's blog"
theme = "PaperMod"

[taxonomies]
  tag = "tags"
#   category = "categories"
  series = "series"

[params]
    ShowMenu = true
    ShowBreadCrumbs = true
    ShowReadingTime = true
    ShowPostNavLinks = true

    [params.homeInfoParams]
        Title = "Hi there"
        Content = "Welcome to my blog. Here you can read some stuff I learned about statistics and environment!"

    [[params.socialIcons]]
        name = "facebook"
        url = "https://www.facebook.com/bich.uyen.643513"

    [params.cover]
        linkFullImages = true

[menu]
    # [[menu.main]]
    #     identifier = "categories"
    #     name = "Categories"
    #     url = "/categories/"
    #     weight = 10

    [[menu.main]]
        identifier = "series"
        name = "Series"
        url = "/series/"
        weight = 10
    
    [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 20 # used to identify the order of the elements

    [[menu.main]]
        identifier = "archives"
        name = "Archives"
        url = "/archives/"
        weight = 30

    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 40

    